# Generated by Django 4.2.1 on 2023-06-28 11:11

from django.db import migrations, models
import django.db.models.deletion
import shop.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='название')),
                ('image', models.ImageField(null=True, upload_to=shop.models.category_icons_directory_path, verbose_name='иконка')),
                ('sort_index', models.PositiveIntegerField(default=0, verbose_name='индекс сортировки')),
                ('active', models.BooleanField(default=False, verbose_name='статус активности')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['sort_index'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='наименование')),
                ('sort_index', models.IntegerField(default=0, verbose_name='индекс сортировки')),
                ('preview', models.ImageField(blank=True, null=True, upload_to=shop.models.product_preview_directory_path, verbose_name='просмотр')),
                ('description', models.TextField(blank=True, default='', verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='цена')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='кол-во')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('is_published', models.BooleanField(default=False, verbose_name='публикация')),
                ('sold', models.PositiveIntegerField(default=0, verbose_name='продано')),
                ('free_delivery', models.BooleanField(default=False, verbose_name='бесплатная доставка')),
                ('reviews', models.PositiveIntegerField(default=0, verbose_name='отзывы')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='скидка')),
                ('limited', models.BooleanField(default=False, verbose_name='ограниченный тираж')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='категория товара')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товар',
                'ordering': ['name', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
            ],
            options={
                'verbose_name': 'магазин',
                'verbose_name_plural': 'магазины',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='название')),
                ('image', models.ImageField(null=True, upload_to=shop.models.subcategory_icons_directory_path, verbose_name='иконка')),
                ('sort_index', models.PositiveIntegerField(default=0, verbose_name='индекс сортировки')),
                ('active', models.BooleanField(default=False, verbose_name='статус активности')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'подкатегория',
                'verbose_name_plural': 'подкатегории',
                'ordering': ['sort_index'],
            },
        ),
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='тип спецификации')),
                ('value', models.CharField(max_length=100, verbose_name='значение')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='товар')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salePrice', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='скидочная цена')),
                ('dateFrom', models.DateField(verbose_name='дата старта')),
                ('dateTo', models.DateField(verbose_name='дата окончания')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'скидка',
                'verbose_name_plural': 'скидки',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='автор отзыва')),
                ('email', models.EmailField(max_length=254, verbose_name='email автора')),
                ('text', models.TextField(verbose_name='текст отзыва')),
                ('rate', models.PositiveIntegerField(choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Средне'), (4, 'Хорошо'), (5, 'Отлично')], verbose_name='оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=shop.models.item_image_directory_path)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop', verbose_name='магазин'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.subcategory', verbose_name='подкатегория товара'),
        ),
    ]
