# Generated by Django 4.2.1 on 2023-06-28 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('fullName', models.CharField(max_length=100, null=True, verbose_name='полное имя')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='e-mail')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='телефон')),
                ('city', models.CharField(max_length=100, null=True, verbose_name='город')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='адрес')),
                ('paymentType', models.CharField(max_length=50, null=True, verbose_name='тип оплаты')),
                ('totalCost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='полная стоимость')),
                ('status', models.CharField(default='not_accepted', max_length=50, verbose_name='статус заказа')),
                ('deliveryType', models.CharField(default='ordinary', max_length=20, verbose_name='тип доставки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='номер карты')),
                ('name', models.CharField(max_length=100, verbose_name='имя владельца карты')),
                ('payment', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='сумма платежа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order', verbose_name='заказ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'платеж',
                'verbose_name_plural': 'платежи',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='стоимость')),
                ('count', models.PositiveIntegerField(verbose_name='кол-во')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product', verbose_name='позиция заказа')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'позиция в заказе',
                'verbose_name_plural': 'позиции в заказе',
            },
        ),
    ]
